### ISSUE TITLE
Heartland payment system using BBPOS chipper c2x

### ISSUE THREAD

**Issue by sandeep3090** [hps/heartland-ios#33]
BBPOS chipper c2x Implementation with Xcode 11(Xcode-11.2.1).

Couple questions pertaining to the integration.
1. Is it recommended to use Xcode 12?
2. Suppose, if we are using Xcode 11, we see these issues:
- The  GlobalMobileSDK can not be compiled in the Xcode 11 version.
- Identifying exact dependencies to compile Heartland SDK on Xcode 11

3.  Suppose we resolve dependencies

- Is there any online api reference that helps us to make tokenization payments using BBPOS ?
- What is the requestAIDSelection method? How can we process that?

Xcode version- 11.2.1
COCOAPODS:- 1.10.1

2.1 ref
<img width="373" alt="bbpos" src="https://user-images.githubusercontent.com/64060151/129440599-3bb786f6-d65b-4bc6-b98b-c252b777678f.png">

**Comment by securesubmit-buildmaster** [comment]
The Heartland iOS SDK has the same requirements for iOS 11 and Xcode 12 as the GlobalMobileSDK dependency as those requirements are due to GlobalMobileSDK.

For your additional questions:

> Is there any online api reference that helps us to make tokenization payments using BBPOS ? 

It's typically advised to handle using tokens for payments separately from the C2X integration. Here is some documentation to complete these requests: https://developer.heartlandpaymentsystems.com/Documentation/credit-card-payments

> What is the requestAIDSelection method? How can we process that?

AID selection is a part of the EMV transaction flow when the card and the reader both support more than one EMV application / AID. The cardholder should be prompted to select the desired AID, and your application would need to provide that selection back to our SDK. Your code will not interact directly with the requestAIDSelection method. You will receive the list of available AIDs via the transaction delegate's onConfirmApplication method, and you will need to provide the selected AID via the device's confirmApplication method.

**Comment by sandeep3090** [comment]
Can you provide GlobalMobileSDK with BBPOS implementation and compatible with Xcode-11

**Comment by securesubmit-buildmaster** [comment]
@sandeep3090 We are unable to provide Xcode 11 compatibility at this time.
